add_newline = false
command_timeout = 2000

format = """$username$hostname$kubernetes$directory$git_branch$python$time
$character
"""

[character]
success_symbol = "▶▶▶"
error_symbol = "[▶▶▶](bold red)"

[username]
style_user = 'bold #a1e3b3'
style_root = 'bold red'
format = '[$user]($style) '
disabled = false
show_always = true

[hostname]
ssh_only = true
format = '[|](bright-black bold) [$hostname](bold #a1e3b3) '
disabled = false

[directory]
truncation_length = 0
truncation_symbol = '…/'
home_symbol = '~'
read_only = ' '
format = '[|](bright-black bold) [$path]($style)[$read_only]($read_only_style) '
style = 'bold #5fd980'

[git_branch]
symbol = '󰊢 '
format = '[|](bright-black bold) [$symbol\[$branch\]]($style) '
style = 'bold green'

[kubernetes]
format = '[|](bright-black bold) [󱃾 $context\($namespace\)](bold purple) '
disabled = false

[python]
symbol = ' '
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']
format = '[|](bright-black bold) [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '

[time]
disabled = false
format = '[|](bright-black bold) [$time]($style) '
time_format = "%T"
style = "bold blue"

# Disabled modules
[git_status]
disabled = true
[vagrant]
disabled = true
[docker_context]
disabled = true
[helm]
disabled = true
[nodejs]
disabled = true
[ruby]
disabled = true
[terraform]
disabled = true
